### ISSUE TITLE
js.org domain?

### ISSUE THREAD

**Issue by mikeal** [request/request.github.io#6]
Would we want to do this site at `request.js.org`? Open source projects can get cname's pretty easily on that.

**Comment by analog-nico** [comment]
We already got this domain. I believe it was you who made it happen. 😉

I think we should rename this repo.

**Comment by simov** [comment]
Yep, it was suggested by Mikeal back then and I made the PR over to the js.org repository. Renaming the repository is a good idea, I just want to make sure @demurgos is aware of that, because he is currently working on it.

**Comment by demurgos** [comment]
Hi, thank you for notifying me. No problem for me.

**Comment by simov** [comment]
I just renamed it, everyone should update their github remotes.
